# Site settings
title: Erik Sandrén
description: "Erik Sandrén programmer with interest in real time graphics, Motion capture and other cool stuff"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.hackerman.se" # the base hostname & protocol for your site
twitter_username: tistatos_
github_username:  tistatos
# Build settings
markdown: kramdown

collections:
 portfolio:
  output: true
